export const teachers = [
  { name: "Agnete Monrad", initials: "Ag" },
  { name: "Andreas Svendgaard Kristensen", initials: "AK" },
  { name: "Anja Møller Vikær", initials: "MV" },
  { name: "Anne Dissing Sandal", initials: "AS" },
  { name: "Anne Møller Jensen", initials: "AMJ" },
  { name: "Barbara M. W. von Loebenstein", initials: "BW" },
  { name: "Birgitte Bjerre Lassen", initials: "BB" },
  { name: "Birgitte Nors", initials: "BN" },
  { name: "Carsten Bøgh Normann Gade", initials: "CG" },
  { name: "Cathrine Wederkinch", initials: "CWe" },
  { name: "Cecilie Vahlstrup", initials: "CV" },
  { name: "Charlotte Hindsgaul", initials: "CHi" },
  { name: "Charlotte Jacobsen Day", initials: "CD" },
  { name: "Christiane Brøchner", initials: "CB" },
  { name: "Clara Fredslund Jürgens Kier", initials: "CK" },
  { name: "Claus Just Andersen", initials: "CJ" },
  { name: "Cæcilie Eskildsen", initials: "CE" },
  { name: "Dan Enevold Mikkelsen", initials: "DM" },
  { name: "Doris Hostrup", initials: "DH" },
  { name: "Ellen Rokkjær", initials: "EK" },
  { name: "Else Marie Gejl", initials: "EG" },
  { name: "Emil Enderup Petersen-Friis", initials: "EF" },
  { name: "Emilie Stenholt Krogh", initials: "ES" },
  { name: "Frank Carlsen", initials: "FC" },
  { name: "Grete Ravn Nielsen", initials: "GR" },
  { name: "Hanne Stenholt Krogh", initials: "HK" },
  { name: "Hans Christian Hulvej", initials: "HC" },
  { name: "Helene K. Græsdal Thomsen", initials: "HG" },
  { name: "Helle Løvgreen", initials: "HLg" },
  { name: "Ida Høegh Kallesøe", initials: "IK" },
  { name: "Igor Teplyi", initials: "Te" },
  { name: "Inge Anne Bækgaard Junker", initials: "IJ" },
  { name: "Jakob Glenstrup Jensby", initials: "JJ" },
  { name: "Janne Bundgaard Ladegaard", initials: "JB" },
  { name: "Jeanette Mikkelsen", initials: "JM" },
  { name: "Jens Schmidt", initials: "JSc" },
  { name: "Jens Aarup Rasmussen", initials: "JR" },
  { name: "Jesper Dahl Johannsen", initials: "Jo" },
  { name: "Jesper Damm", initials: "JDa" },
  { name: "Jesper Thor Larsen", initials: "JL" },
  { name: "Joachim Kroun", initials: "JKr" },
  { name: "Jytte Nygaard Mikkelsen", initials: "JMi" },
  { name: "Jørn Riis", initials: "Ri" },
  { name: "Katrine Sixtus Kuriakose", initials: "KK" },
  { name: "Kenneth Bozkurt Madsen", initials: "KM" },
  { name: "Kirsten Skov", initials: "KS" },
  { name: "Klavs Skjold Øster", initials: "KØ" },
  { name: "Lene Secher", initials: "LSe" },
  { name: "Line Pihlkjær Rasmussen", initials: "LR" },
  { name: "Lise Wich", initials: "LW" },
  { name: "Lotte Genefke", initials: "LG" },
  { name: "Louise Gjerlev Jensen", initials: "LJ" },
  { name: "Louise Højgaard Marcussen", initials: "Lo" },
  { name: "Mads Engblad Clemmensen", initials: "MC" },
  { name: "Marie Louise Sibast", initials: "MS" },
  { name: "Marie Thorsen", initials: "MT" },
  { name: "Martin Stenstrup Hangaard", initials: "MSH" },
  { name: "Mette Tetzschner Vinther", initials: "Vi" },
  { name: "Mia Louise L. Sand", initials: "Mi" },
  { name: "Mie Lindeman Olsen", initials: "MO" },
  { name: "Mikkel Hollænder Jensen", initials: "HJ" },
  { name: "Mikkel Løve Nørgaard", initials: "ML" },
  { name: "Mikkel Pedersen", initials: "MP" },
  { name: "Niels Erik Jensen", initials: "NJ" },
  { name: "No Name", initials: "NN" },
  { name: "Noah Paludan", initials: "NP" },
  { name: "Per Selmann Andreassen", initials: "PA" },
  { name: "Per Thaaning Fløng", initials: "PF" },
  { name: "Pernille Lærke Munk-Hansen", initials: "PM" },
  { name: "Peter Synnestvedt Jepsen", initials: "PJ" },
  { name: "Rikke Forsberg", initials: "RF" },
  { name: "Rita Cassøe Malakha Thomassen", initials: "RT" },
  { name: "Rosita Seeberg", initials: "RS" },
  { name: "Rune Dueholm Bådsgård", initials: "RB" },
  { name: "Sebastian Fogh Nordentoft", initials: "SF" },
  { name: "Selma Langdahl Christiansen", initials: "LC" },
  { name: "Simon Vaaben Andersen", initials: "SA" },
  { name: "Simone Leidinger", initials: "SL" },
  { name: "Sine Tølbøll Jensen", initials: "ST" },
  { name: "Sofie Grønning", initials: "SG" },
  { name: "Steen Vang Petersen", initials: "SV" },
  { name: "Stine Fisker Mortensen", initials: "Fi" },
  { name: "Stine Nue Mikkelsen", initials: "SM" },
  { name: "Susann Ann Stabell", initials: "SAS" },
  { name: "Søren Vrist Christensen", initials: "SC" },
  { name: "Thomas Lund", initials: "TL" },
  { name: "Thomas Skotting", initials: "TS" },
  { name: "Tina Myrup Kristensen", initials: "TK" },
  { name: "Torben Hviid", initials: "TH" },
  { name: "Trine Noe Jacobsen", initials: "TN" },
  { name: "Troels Hedegaard", initials: "He" },
  { name: "Ulrik Lyng Vestergaard", initials: "UV" },
  { name: "Vibeke Rasmussen", initials: "VRa" },
  { name: "Zana Tahsen", initials: "ZT" },
];
